#!/bin/bash

#PBS -l nodes=1:ppn=8,vmem=150gb
#PBS -l walltime=100:00:00

module load singularity



#time singularity run /N/u/brlife/Carbonate/steklov-py2-2017-10-23-7c5e6fddeda0.img
time singularity run /N/u/brlife/Carbonate/steklov-py2-2017-10-25-ab26d6e2a794.img
if [ ! -s spectrum.json ];
then
	echo "spectrum.json missing"
	exit 1
fi
