#!/bin/bash

#PBS -l nodes=1:ppn=8,vmem=64gb
#PBS -l walltime=10:00:00

module load singularity

#param=$(jq -r .param config.json)
#time singularity exec /N/u/brlife/Carbonate/steklov-py2-2017-10-19-78cd14f43d8b.img -param $param
#time singularity run /N/u/brlife/Carbonate/steklov-py2-2017-10-19-7caf15d2f5fb.img
time singularity run /N/u/brlife/Carbonate/steklov-py2-2017-10-23-a4e86c7ebe7b.img
if [ ! -s spectrum.json ];
then
	echo "spectrum.json missing"
	exit 1
fi
